//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamroMaat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bl_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bl_Order()
        {
            this.bl_OrderProduct = new HashSet<bl_OrderProduct>();
        }
    
        public int or_id { get; set; }
        public string or_username { get; set; }
        public string or_phone_no { get; set; }
        public string or_email { get; set; }
        public Nullable<System.DateTime> or_create_time { get; set; }
        public Nullable<bool> or_approved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bl_OrderProduct> bl_OrderProduct { get; set; }
    }
}
