//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneToOne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_profiles
    {
        public int user_id { get; set; }
        public string profile_data { get; set; }
    
        public virtual user user { get; set; }
    }
}
