//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrUDoperation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeDetail
    {
        public int id { get; set; }
        [Required]
        [RegularExpression("^[a-zA-Z0-9][a-zA-Z0-9.,'\\-_ ]*[a-zA-Z0-9]$", ErrorMessage = "*Name is not valid.")]
        public string Name { get; set; }
        public string address { get; set; }
        public string field { get; set; }
    }
}
