//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUploadModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_Path
    {
        public int id { get; set; }
        public string path { get; set; }
    }
}
