//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fileUplood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_Path
    {
        internal readonly string FileName;

        public string Files { get; set; }
        public string Message { get; set; }
        public int ContentLength { get; internal set; }

        internal void SaveAs(string path)
        {
            throw new NotImplementedException();
        }
    }
}
