//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int std_id { get; set; }
        public string std_name { get; set; }
        public string std_contact { get; set; }
        public string std_age { get; set; }
        public Nullable<int> ad_id_fk { get; set; }
    
        public virtual Adminn Adminn { get; set; }
    }
}
