//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadFileSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class UserFile
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }

        public HttpPostedFileBase httpPostedFileBases { get; set; }

        
    }
}
