//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamro_Bazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bl_catagory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bl_catagory()
        {
            this.bl_product = new HashSet<bl_product>();
        }
    
        public int cat_id { get; set; }
        public string cat_name { get; set; }
        public string cat_color { get; set; }
        public string cat_icon { get; set; }
        public Nullable<System.DateTime> cat_create_done { get; set; }
        public Nullable<int> cat_fk_Ad_id { get; set; }
    
        public virtual bl_Admin bl_Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bl_product> bl_product { get; set; }
    }
}
