//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamro_Bazar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bl_OrderProduct
    {
        public int op_id { get; set; }
        public Nullable<int> op_pro_id { get; set; }
        public Nullable<int> op_qty { get; set; }
        public Nullable<int> op_unitprice { get; set; }
        public Nullable<int> op_total { get; set; }
        public Nullable<int> op_fk_or_id { get; set; }
    
        public virtual bl_Order bl_Order { get; set; }
        public virtual bl_product bl_product { get; set; }
    }
}
